version: '3'
networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: bitnami/mongodb:6.0.0
    networks:
      - app-tier
    ports:
      - 27017:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_ROOT_PASSWORD=password123
